export const BURGER_BUTTON_CLASS = "burger__button"
export const BURGER_CLOSE_BUTTON_CLASS = "burger-menu__close"
export const BURGER_MENU_CLASS = "burger-menu"
export const BURGER_MENU_ACTIVE_CLASS = "burger-menu__active"
export const BURGER_MENU_LINK_CLASS = "menu__link"